title: Jquery TextTyper
description: TextTyper is a jQuery plugin to animate your text just like typewriter.
google_analytics: UA-12742399-5
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
